language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.5
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python manage.py test
