language: python
python:
  - "2.6"
  - "2.7"
env:
  global:
  - DJANGO="1.5"
  - DJANGO_SETTINGS_MODULE="experimentdb.settings"
  - PIP_USE_MIRRORS=true

# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python manage.py test
